spring.application.name=eventmanagement

server.port=8081

spring.datasource.url=jdbc:h2:mem:campus_events_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.open-in-view=false

# Defer SQL script execution until Hibernate has created the schema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nanireddy.admin@gmail.com
spring.mail.password=pttkvdtyhwizbouc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mvc.hiddenmethod.filter.enabled=true
